version: '3.8'

services:
  snipely-bot:
    build: .
    container_name: snipely
    restart: unless-stopped
    volumes:
      # Dit is de magie: koppel jouw lokale 'data' map aan de 'data' map in de container
      - ./data:/app/data